### PR TITLE
Additional release changes and bug fixes

### LINKED ISSUE #36: Instructional trial time stamps are broken
Time stamp of image trials happens at loading, not when they actually appear on the screen.

### LINKED ISSUE #58: Output for instruction trials
It doesn't seem that the output for instructions is working? Maybe this is another branch?

### LINKED ISSUE #68: Change all references of "Mazes" to "Enclosures"
Need to change all references to Mazes to Enclosures and Enclosure (currently MazeName) should be change to call the index of the Enclosure from "Enclosures" section below. 

Trial call should be

"Enclosure" : x  (where x is an integer = index of the enclosure in the "Enclosures" section)

"Mazes" Section should be changed to "Enclosures". 
"Mazes" : []    should be changed to:     "Enclosures" : []
The Enclosure index number that is being used during the trial should be output to the data file

### LINKED ISSUE #69: Goal Parameters "Type" and "Image"
"Type" should be "3D" or "2D" 
"Image" should be changes to "Object" 
If type = 2D then "Object" should refer to 2D_Objects folder
if Type = 3D then "Object should reference 32_Objects folder.

### PR DESCRIPTION
**Pull request by codyhowarth**
## Description

Making some changes that were suggested by reviewers.

## Motivation and Context

- Closes #36, Closes #58, Closes #68, Closes #69.
- Fixes issue when trying to run python scripts from a path that contains a space.

## How Has This Been Tested?

- Manually by @kbnealy 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: Assets/Scripts/wallSystem/PickupGenerator.cs [hunk 1]
```diff
@@ -15,9 +15,10 @@ public class PickupGenerator : MonoBehaviour
 
         private static Data.Point ReadFromExternal(string inputFile)
         {
+            var scriptPath = DataSingleton.GetData().PythonScriptsPath + inputFile;
             var p = new Process
             {
-                StartInfo = new ProcessStartInfo("python", DataSingleton.GetData().PythonScriptsPath + inputFile)
+                StartInfo = new ProcessStartInfo("python", "\"" + scriptPath + "\"")
```
Comment (codyhowarth) [inline Assets/Scripts/wallSystem/PickupGenerator.cs:21]: @kbnealy if you're curious this was the fix for the python script path.
